services:
  - type: web
    name: event-manager
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: event-manager-fraediaz.onrender.com
      - key: WEB_CONCURRENCY
        value: 2
